# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# sys.path path, will be prepended to sys.path if present.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# leave blank for localtime
# timezone =

# max length of characters to apply to the "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during the 'revision' command
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without a source .py file
# sourceless = false

# version path separator; default is "os" (uses os.pathsep)
version_path_separator = os

# sqlalchemy.url is configured dynamically by migrations/env.py
# Placeholder below, do NOT use directly
sqlalchemy.url = driver://user:pass@host:5432/dbname


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.

# format using "black"
# hooks = black
# black.type = console_scripts
# black.entrypoint = black


[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %%(levelname)-5.5s [%%(name)s] %%(message)s
datefmt = %%H:%%M:%%S
