"""initial_migration

Revision ID: 1a529a0f1cbd
Revises: 
Create Date: 2026-05-16 21:08:34.967205

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a529a0f1cbd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_configs', sa.Column('enable_max_days_constraint', sa.Boolean(), nullable=False, server_default='false', comment='是否启用最大监考天数约束'))
    op.add_column('schedule_configs', sa.Column('enable_day_continuity_constraint', sa.Boolean(), nullable=False, server_default='false', comment='是否启用日期连续性约束'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_configs', 'enable_day_continuity_constraint')
    op.drop_column('schedule_configs', 'enable_max_days_constraint')
    # ### end Alembic commands ###
