"""add exam_date to time_slots and schedule_config

Revision ID: 6884e3d3c637
Revises: 971e7b161b7c
Create Date: 2026-05-21 17:50:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6884e3d3c637'
down_revision = '971e7b161b7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_configs', sa.Column('exam_start_date', sa.Date(), nullable=True, comment='考试起始日期'))
    op.add_column('schedule_configs', sa.Column('exam_weeks', sa.Integer(), nullable=False, server_default='1', comment='考试周数 (1-4)'))
    op.add_column('time_slots', sa.Column('exam_date', sa.Date(), nullable=True, comment='考试具体日期 (多周排考时使用, null 表示模板记录)'))
    op.create_index(op.f('ix_time_slots_exam_date'), 'time_slots', ['exam_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_time_slots_exam_date'), table_name='time_slots')
    op.drop_column('time_slots', 'exam_date')
    op.drop_column('schedule_configs', 'exam_weeks')
    op.drop_column('schedule_configs', 'exam_start_date')
    # ### end Alembic commands ###
