"""add max_days to schedule_config

Revision ID: 971e7b161b7c
Revises: 1a529a0f1cbd
Create Date: 2026-05-19 09:16:42.400179

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971e7b161b7c'
down_revision = '1a529a0f1cbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_configs', sa.Column('max_days', sa.Integer(), nullable=False, server_default='3', comment='最大监考天数上限'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_configs', 'max_days')
    # ### end Alembic commands ###
