"""add ab_major_preference to schedule_config

Revision ID: 9b84789eae36
Revises: 971e7b161b7c
Create Date: 2026-06-10 16:05:00.000000

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b84789eae36'
down_revision = '971e7b161b7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule_configs', sa.Column('ab_major_preference', sa.Boolean(), nullable=False, server_default='false', comment='AB卷同专业集中偏好'))
    op.add_column('schedule_configs', sa.Column('ab_major_tolerance', sa.Float(), nullable=False, server_default='0.15', comment='AB卷同专业集中的人数均衡容忍度'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule_configs', 'ab_major_tolerance')
    op.drop_column('schedule_configs', 'ab_major_preference')
    # ### end Alembic commands ###
